import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { Toaster } from "sonner";
import NavbarWrapper from "@/components/navbarWrapper";
import { Providers } from "@/components/themeProviders";
import { I18nProviderClient } from "@/locales/client";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
  params
}: Readonly<{
  children: React.ReactNode;
  params: Promise<{ locale: string }>
}>) {
  const locale = (await params).locale
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased `}
      >
        <I18nProviderClient locale={locale}>

          <Providers >

            <Toaster richColors position="top-right" closeButton />

            <div className="h-screen grid grid-rows-[10%_1fr] " >
              <NavbarWrapper />
              {children}
            </div>

          </Providers>
        </I18nProviderClient>

      </body>
    </html>
  );
}
